### ISSUE TITLE
Jupyter kernel keeps dying

### ISSUE THREAD

**Issue by avajimm** [1297rohit/VGG16-In-Keras#2]
Hi

I was trying to run this project on jupyter notebook that I set up on ec2 t2.small instance, but the kernel keeps dying after model.fit_generator is supposed to run. 

The message I get in command line is

_KernelRestarter: restarting kernel (1/5), keep random ports
Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA_

While I know it is just a warning and it should run just fine, I have no clue why the kernel keeps dying.

Any help is appreciated.

**Comment by 1297rohit** [comment]
Hello,
The issue maybe with the memory availability. Try to change the batch size and step size. Play with the batch size and step size till you find right values for your machines configuration.

**Comment by avajimm** [comment]
UPD: Hi

I changed my instance to t2.xlarge and it seems to be working fine now :)

> Hello
> 
> I tried to change this, but kernel still eventually dies.
> 
> Can you please specify which versions of python and tensorflow to use? For the very first time I believe I used the latest, but then I learned that from tensorflow 2.2.0 fit_generator was deprecated. For this reasons I changes tensorflow to 1.15 and python to 3.7
> 
> Now I get new message as follows
> 
> > I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
> > To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
> > 2020-07-02 12:36:44.855418: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400070000 Hz
> > 2020-07-02 12:36:44.855638: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55abac90d1e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> > 2020-07-02 12:36:44.855660: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> > OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0
> > OMP: Info #214: KMP_AFFINITY: decoding x2APIC ids.
> > OMP: Info #156: KMP_AFFINITY: 1 available OS procs
> > OMP: Info #157: KMP_AFFINITY: Uniform topology
> > OMP: Info #285: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
> > OMP: Info #285: KMP_AFFINITY: topology layer "L3 cache" is equivalent to "socket".
> > OMP: Info #285: KMP_AFFINITY: topology layer "L2 cache" is equivalent to "socket".
> > OMP: Info #285: KMP_AFFINITY: topology layer "L1 cache" is equivalent to "socket".
> > OMP: Info #285: KMP_AFFINITY: topology layer "core" is equivalent to "socket".
> > OMP: Info #285: KMP_AFFINITY: topology layer "thread" is equivalent to "socket".
> > OMP: Info #191: KMP_AFFINITY: 1 socket x 1 core/socket x 1 thread/core (1 total cores)
> > OMP: Info #216: KMP_AFFINITY: OS proc to physical thread map:
> > OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to socket 0
> > OMP: Info #252: KMP_AFFINITY: pid 27132 tid 27132 thread 0 bound to OS proc set 0
> > 2020-07-02 12:36:44.857412: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
