### ISSUE TITLE
How to predict more than 2 classes in the end? 

### ISSUE THREAD

**Issue by hashimi1998** [1297rohit/VGG16-In-Keras#4]
Helo, I need help. How to add more classes in the output below? I have 6 different classes of plant and i do not know how to edit at the end.

from keras.models import load_model
saved_model = load_model("VGG16_Model_FYP.h5")
output = saved_model.predict(img)
if output[0][0] > output[0][1]:
    print("Kacip Fatimah")
else:
    print('Mempisang')

**Comment by 1297rohit** [comment]
You can use numpy.argmax to find which index is having highest value and identify classes accordingly.
